### ISSUE TITLE
Знакомство с ES6

### ISSUE THREAD

**Issue by TFK70** [atls-academy/lessatia.github.io#3]
### Задача

Ознакомиться с [ES6 синтаксисом](https://frontend-stuff.com/blog/es6/)

В частности с модульным javascript. Сделать следующее задание:

1. Сделать функцию sum, суммирующую 2 числа и вынести ее в отдельный модуль
2. Импортировать эту функцию в другом модуле и сложить 2 числа
3. Вывести результат в консоль

Можно приложить ссылку на сендбокс с выволненным заданием

**Comment by lessatia** [comment]
https://github.com/lessatia/Atlantis_academy/tree/main/Module_export 

У меня вопрос
если npm аналог yarn и нужен для разделения пространства, (то же это ли самое что и вынесение функций в отдельные модули и потом присоединение их с помощью  module.exports или воркспейс это другое), то в каком месте мы прописываем это в pacage,json?

**Comment by TFK70** [comment]
@lessatia получилось выполнить код выше?

**Comment by lessatia** [comment]
@TFK70 @TFK70   так?
https://github.com/lessatia/Atlantis_academy/tree/main/Module_export  я читаю по ссылкам что ты прислал чтобы понимать  package.json, а не использовать его методом втыка в него подходящих строк
