### ISSUE TITLE
Ознакомиться с Workspaces в yarn

### ISSUE THREAD

**Issue by lessatia** [atls-academy/lessatia.github.io#4]
Ознакомиться с Workspaces в yarn

Завести проект с 0, посоздавать там воркспейсы, зависимости в них поставить,
за примером можно сюда глянуть - https://github.com/torin-asakura/misik

**Comment by lessatia** [comment]
@TFK70 
https://github.com/lessatia/Atlantis_academy/tree/main/Module_export
я переделала прошлое задание про модули в воркспейсы и поставила зависимость,

**Comment by TFK70** [comment]
@lessatia Хорошо, теперь перенеси все в отдельный воркспейс в этой репе. Создай pull request к 
этой задаче и закрой ее

**Comment by lessatia** [comment]
https://github.com/atls-academy/lessatia.github.io/pull/7
